### ISSUE TITLE
Build is break

### ISSUE THREAD

**Issue by dionysiosarvanitis** [mdbootstrap/mdb-ui-kit#1060]
Seems like build is still broken, after the latest ES6 updates.

```
Requiring external module babel-core/register
Working directory changed to ~\github\bootstrap-material-design
\github\bootstrap-material-design\node_modules\babel-core\lib\transformation\file\index.js:591
      throw err;
      ^

SyntaxError: /github/bootstrap-material-design/node_modules/stream-exhaust/index.js: Argument name clash in strict mode (32:36)
  30 | inherits(Sink, Writable);
  31 |
> 32 | Sink.prototype._write = function(_, _, cb) {
     |                                     ^
  33 |   setImmediate(cb);
  34 | };
  35 |
    at Parser.pp.raise (\github\bootstrap-material-design\node_modules\babylon\lib\parser\location.js:22:13)
    at Parser.pp.checkLVal (\github\bootstrap-material-design\node_modules\babylon\lib\parser\lval.js:257:16)
    at Parser.pp.parseFunctionBody (\github\bootstrap-material-design\node_modules\babylon\lib\parser\expression.js:996:14)
    at Parser.pp.parseFunction (\github\bootstrap-material-design\node_modules\babylon\lib\parser\statement.js:647:8)
    at Parser.pp.parseFunctionExpression (\github\bootstrap-material-design\node_modules\babylon\lib\parser\expression.js:532:17)
    at Parser.pp.parseExprAtom (\github\bootstrap-material-design\node_modules\babylon\lib\parser\expression.js:494:19)
    at Parser.pp.parseExprSubscripts (\github\bootstrap-material-design\node_modules\babylon\lib\parser\expression.js:277:19)
    at Parser.pp.parseMaybeUnary (\github\bootstrap-material-design\node_modules\babylon\lib\parser\expression.js:257:19)
    at Parser.pp.parseExprOps (\github\bootstrap-material-design\node_modules\babylon\lib\parser\expression.js:188:19)
    at Parser.pp.parseMaybeConditional (\github\bootstrap-material-design\node_modules\babylon\lib\parser\expression.js:165:19)
    at Parser.pp.parseMaybeAssign (\github\bootstrap-material-design\node_modules\babylon\lib\parser\expression.js:128:19)
```

**Comment by FezVrasta** [comment]
How do you reproduce this problem?

**Comment by dionysiosarvanitis** [comment]
Sorry. Trying to make a clean install fixes build problems. But now I'm stuck on browserify build while importing with a `require('bootstrap-material-design')`.

```
\node_modules\bootstrap\js\src\alert.js:1
import Util from './util'
^
ParseError: 'import' and 'export' may appear only with 'sourceType: module'
```

and 

```
 [SyntaxError: Unexpected token (4:7) while parsing \node_modules\bootstrap\js\src\tooltip.js
```

Reverting "import BS sources" to the one line `import 'bootstrap/dist/js/bootstrap'` and building again fixes the problem.

**Comment by FezVrasta** [comment]
If the build works, the problem seems to be in your own code. I can accept PR if you find a way to make the code compile even on different environments but I wouldn't say it's a bug.
