### ISSUE TITLE
V4 - Unable to generate compiled JS

### ISSUE THREAD

**Issue by gargaseem** [mdbootstrap/mdb-ui-kit#1178]
![gitscreenshot from 2017-05-05 11-59-23](https://cloud.githubusercontent.com/assets/2574435/25735624/5c51a742-318a-11e7-8a7d-99eb270e9223.png)
**I am trying to compile the source to get JS using gulp but I am getting the following error (sytanx error in bootstrap's tooltip.js):**

```
events.js:72
        throw er; // Unhandled 'error' event
              ^
SyntaxError: Unexpected token (4:7) while parsing /var/www/html/amrtyu/node_modules/bootstrap/js/src/tooltip.js while parsing file: /var/www/html/amrtyu/node_modules/bootstrap/js/src/tooltip.js
    at DestroyableTransform.end [as _flush] (/var/www/html/amrtyu/node_modules/browserify/node_modules/insert-module-globals/index.js:96:21)
    at DestroyableTransform.<anonymous> (/var/www/html/amrtyu/node_modules/browserify/node_modules/readable-stream/lib/_stream_transform.js:115:49)
    at DestroyableTransform.g (events.js:180:16)
    at DestroyableTransform.EventEmitter.emit (events.js:92:17)
    at prefinish (/var/www/html/amrtyu/node_modules/browserify/node_modules/readable-stream/lib/_stream_writable.js:503:12)
    at finishMaybe (/var/www/html/amrtyu/node_modules/browserify/node_modules/readable-stream/lib/_stream_writable.js:511:7)
    at endWritable (/var/www/html/amrtyu/node_modules/browserify/node_modules/readable-stream/lib/_stream_writable.js:523:3)
    at DestroyableTransform.Writable.end (/var/www/html/amrtyu/node_modules/browserify/node_modules/readable-stream/lib/_stream_writable.js:493:41)
    at DestroyableTransform.onend (/var/www/html/amrtyu/node_modules/browserify/node_modules/readable-stream/lib/_stream_readable.js:504:10)
    at DestroyableTransform.g (events.js:180:16)
    at DestroyableTransform.EventEmitter.emit (events.js:117:20)
    at endReadableNT (/var/www/html/amrtyu/node_modules/browserify/node_modules/readable-stream/lib/_stream_readable.js:926:12)
```

I am using following gulp code:
```
/*
---- Generate BMD CommonJs
*/
gulp.task('BMDcommonJs', function () {
  return gulp
    .src('./static/scripts/dev/js/bmd/**/*.js', {base: "./static/scripts/dev/js/bmd"})
    //.pipe(babel({
	//	presets: ['es2015']
	//	}))
    .pipe(changed('./static/scripts/dev/js/bmd_processed/', {hasChanged: changed.compareLastModifiedTime}))
    .pipe(gulp.dest('./static/scripts/dev/js/bmd_processed/'));
});

/*
---- Generate BMD Browserify JS
*/
gulp.task('BMDbrowserify', ['BMDcommonJs'], function() {
    //return browserify('./static/scripts/dev/js/bmd_processed/index.js')
    return browserify({
        entries: ['./static/scripts/dev/js/bmd_processed/index.js']
    })
    .transform(babelify.configure({
        presets : ["es2015"]
    }))
        .bundle()
        //Pass desired output filename to vinyl-source-stream
        .pipe(source('bootstrap-material.js'))
        // Start piping stream to tasks!
        .pipe(gulp.dest('./static/scripts/dev/js/includes'));
});
```

My package.json is as follows:
```
{
  "name": "xyz",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "Aseem",
  "license": "ISC",
  "devDependencies": {
    "babel-polyfill": "^6.9.1",
    "babel-preset-es2015": "^6.24.1",
    "babelify": "^7.3.0",
    "browserify": "^13.0.1",
    "gulp": "^3.9.1",
    "gulp-babel": "^6.1.2",
    "gulp-changed": "^1.3.0",
    "gulp-clean-css": "^2.3.2",
    "gulp-concat-multi": "^1.0.0",
    "gulp-jshint": "^2.0.0",
    "gulp-newer": "^1.2.0",
    "gulp-sass": "^2.3.1",
    "gulp-uglify": "^2.0.0",
    "gulp-util": "^3.0.7",
    "tether": "^1.3.3",
    "vinyl-buffer": "^1.0.0",
    "vinyl-source-stream": "^1.1.0"
  },
  "babel": {
    "presets": [
      "es2015",
      "react"
    ]
  }
}
```

**Comment by FezVrasta** [comment]
As far I see the error is coming from Bootstrap JS, and not from the build setup provided by this project. I'm not sure I can help here.
