### ISSUE TITLE
bower.json error when installing 4.0.0-beta.3

### ISSUE THREAD

**Issue by roedtogsvart** [mdbootstrap/mdb-ui-kit#1236]
I'm not sure what this error is but it seems it's a problem with the bower.json file.  Here's a full output from my CLI:

$ bower install -V bootstrap-material-design#v4.0.0-beta.3
bower cached        https://github.com/FezVrasta/bootstrap-material-design.git#4.0.0-beta.3
bower validate      4.0.0-beta.3 against https://github.com/FezVrasta/bootstrap-material-design.git#v4.0.0-beta.3
bower not-cached    https://github.com/twbs/bootstrap.git#v4-dev
bower resolve       https://github.com/twbs/bootstrap.git#v4-dev
bower cached        https://github.com/jquery/jquery-dist.git#2.2.4
bower validate      2.2.4 against https://github.com/jquery/jquery-dist.git#^2.2
bower cached        https://github.com/FezVrasta/popper.js.git#1.12.5
bower validate      1.12.5 against https://github.com/FezVrasta/popper.js.git#^1.10.11
bower download      https://github.com/twbs/bootstrap/archive/v4-dev.tar.gz
bower extract       bootstrap#v4-dev archive.tar.gz
bower EMALFORMED    Failed to read /tmp/dev/bower/ca4c50b905dc21ea17a10549a6f5944f-24940-YhCPGr/bower.json

Additional error details:
Unexpected token @ in JSON at position 0

Stack trace:
SyntaxError: Unexpected token @ in JSON at position 0
    at Object.parse (native)
    at /usr/lib/node_modules/bower/lib/node_modules/bower-json/lib/json.js:42:29
    at /usr/lib/node_modules/bower/lib/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:447:3)
From previous event:
    at readJson (/usr/lib/node_modules/bower/lib/util/readJson.js:17:6)
    at GitHubResolver.Resolver._readJson (/usr/lib/node_modules/bower/lib/core/resolvers/Resolver.js:180:12)

Console trace:
Error
    at StandardRenderer.error (/usr/lib/node_modules/bower/lib/renderers/StandardRenderer.js:81:37)
    at Logger.<anonymous> (/usr/lib/node_modules/bower/lib/bin/bower.js:110:26)
    at emitOne (events.js:96:13)
    at Logger.emit (events.js:188:7)
    at Logger.emit (/usr/lib/node_modules/bower/lib/node_modules/bower-logger/lib/Logger.js:29:39)
    at /usr/lib/node_modules/bower/lib/commands/index.js:48:20
    at _rejected (/usr/lib/node_modules/bower/lib/node_modules/q/q.js:844:24)
    at /usr/lib/node_modules/bower/lib/node_modules/q/q.js:870:30
    at Promise.when (/usr/lib/node_modules/bower/lib/node_modules/q/q.js:1122:31)
    at Promise.promise.promiseDispatch (/usr/lib/node_modules/bower/lib/node_modules/q/q.js:788:41)
System info:
Bower version: 1.8.2
Node version: 6.11.3
OS: Linux 4.9.0-3-amd64 x64

**Comment by FezVrasta** [comment]
I don't think the problem comes from this library, our bower.json looks good.

https://github.com/FezVrasta/bootstrap-material-design/blob/v4.0.0-beta.3/bower.json
