### ISSUE TITLE
Menu not working with webpack

### ISSUE THREAD

**Issue by adamwright104** [mdbootstrap/mdb-ui-kit#1297]
webpack

```
const webpack = require("webpack")
const path = require("path")
const CopyWebpackPlugin = require("copy-webpack-plugin")
const CleanWebpackPlugin = require("clean-webpack-plugin")

module.exports = {
  entry: {
    common: "./src/index.js",
    packages: "./src/entry/packages.js",
    suppliers: "./src/entry/suppliers.js",
    supplierForm: "./src/entry/supplier_form.js",
    supplierPackages: "./src/entry/supplier_packages.js",
    tours: "./src/entry/tours.js",
    tourForm: "./src/entry/tour_form.js",
    vendor: ["vue", "jquery", "popper.js", "bootstrap-material-design"],
  },

  output: {
    filename: "[name].js",
    path: path.resolve(__dirname, "../public"),
  },

  module: {
    rules: [{
      test: /\.js$/,
      enforce: "pre",
      use: [
        "eslint-loader",
      ],
    }, {
      test: /\.css$/,
      use: [
        "style-loader",
        { loader: "css-loader", options: { importLoaders: 1 } },
        "postcss-loader",
      ],
    }, {
      test: /\.vue$/,
      loader: "vue-loader",
    }],
  },

  resolve: {
    alias: {
      "vue$": "vue/dist/vue.esm.js",
    },
    extensions: [".js", ".vue"],
  },

  plugins: [
    new webpack.optimize.CommonsChunkPlugin({ name: "vendor" }),
    new CopyWebpackPlugin([{ from: "src/styles/vendor" }]),
    new CleanWebpackPlugin("../public"),
    new webpack.ProvidePlugin({$: "jquery", jQuery: "jquery", "Popper": "popper.js"}),
  ],
}
```

packages

```
"dependencies": {
    "bootstrap-material-design": "^4.1.1",
    "fuse.js": "^3.2.0",
    "jquery": "^3.3.1",
    "popper.js": "^1.12.9",
  },
```

js

```
import $ from "jquery"
window.jQuery = $
window.$ = $
import Popper from "popper.js"
window.Popper = Popper
import "bootstrap-material-design"
import "./components/Snackbar"
import "./styles/app.css"

$(document).ready(() => { $("body").bootstrapMaterialDesign() })
```

Now if i use normal bootstrap instead of material design it works! 

With material design i get the following errors with the above code, what am i missing?

```
Uncaught TypeError: Cannot read property 'modifiers' of undefined
    at bootstrap-material-design.js:6318
    at bootstrap-material-design.js:2
    at Object.<anonymous> (bootstrap-material-design.js:5)
    at Object.14 (bootstrap-material-design.js:6537)
    at __webpack_require__ (bootstrap 531f2276cd3255648494:54)
    at Object.49 (popper.js:2437)
    at __webpack_require__ (bootstrap 531f2276cd3255648494:54)
    at bootstrap 531f2276cd3255648494:149
    at bootstrap 531f2276cd3255648494:149

jquery.js:3818 jQuery.Deferred exception: __WEBPACK_IMPORTED_MODULE_0_jquery___default(...)(...).bootstrapMaterialDesign is not a function TypeError: __WEBPACK_IMPORTED_MODULE_0_jquery___default(...)(...).bootstrapMaterialDesign is not a function
    at HTMLDocument.__WEBPACK_IMPORTED_MODULE_0_jquery___default.ready (http://localhost:9292/common.js:122:127)
    at mightThrow (http://localhost:9292/vendor.js:20996:29)
    at process (http://localhost:9292/vendor.js:21064:12) undefined
jQuery.Deferred.exceptionHook @ jquery.js:3818
process @ jquery.js:3606
setTimeout (async)
(anonymous) @ jquery.js:3640
fire @ jquery.js:3268
fireWith @ jquery.js:3398
fire @ jquery.js:3406
fire @ jquery.js:3268
fireWith @ jquery.js:3398
ready @ jquery.js:3878
completed @ jquery.js:3888
jquery.js:3827 Uncaught TypeError: __WEBPACK_IMPORTED_MODULE_0_jquery___default(...)(...).bootstrapMaterialDesign is not a function
    at HTMLDocument.__WEBPACK_IMPORTED_MODULE_0_jquery___default.ready (index.js:10)
    at mightThrow (jquery.js:3534)
    at process (jquery.js:3602)
__WEBPACK_IMPORTED_MODULE_0_jquery___default.ready @ index.js:10
mightThrow @ jquery.js:3534
process @ jquery.js:3602
setTimeout (async)
jQuery.readyException @ jquery.js:3826
(anonymous) @ jquery.js:3846
mightThrow @ jquery.js:3534
process @ jquery.js:3602
setTimeout (async)
(anonymous) @ jquery.js:3640
fire @ jquery.js:3268
fireWith @ jquery.js:3398
fire @ jquery.js:3406
fire @ jquery.js:3268
fireWith @ jquery.js:3398
process @ jquery.js:3622
setTimeout (async)
(anonymous) @ jquery.js:3640
fire @ jquery.js:3268
fireWith @ jquery.js:3398
fire @ jquery.js:3406
fire @ jquery.js:3268
fireWith @ jquery.js:3398
ready @ jquery.js:3878
completed @ jquery.js:3888
```

**Comment by FezVrasta** [comment]
I think you must use the Plugin provider of webpack to provide jQuery and Popper.js

**Comment by adamwright104** [comment]
@FezVrasta I've tried that 

webpack

`new webpack.ProvidePlugin({$: "jquery", jQuery: "jquery", Popper: "popper.js"}),`

js
```

import "jquery"
import "popper.js"
import "bootstrap-material-design"
import "./components/Snackbar"
import "./styles/app.css"

$(document).ready(() => { $("body").bootstrapMaterialDesign() })
```
Same errors, do you have an example of this working with webpack?

**Comment by adamwright104** [comment]
@FezVrasta i  managed to get it working following https://github.com/FezVrasta/bootstrap-material-design/issues/1296

i have no idea why it works using the umd version

**Comment by hermanho** [comment]
Bootstrap had made the change on the package handling. Should it be applied also?

https://github.com/twbs/bootstrap/commit/9936bf59444c402b653f28449529eab83794e911#diff-ed26e07442324b4bfab597bb9bb85201

**Comment by ajparrah** [comment]
> @FezVrasta i managed to get it working following #1296
> 
> i have no idea why it works using the umd version

Really, Thank you so much!

**Comment by ajparrah** [comment]
I'm using...

### - webpack 4.42.1
### - jquery:  3.2.1
### - popper.js: 1.16.1-lts
### - bootstrap-material-design: 4.1.1

These settings worked for me:

```
new webpack.ProvidePlugin({
      $: 'jquery',
      jQuery: 'jquery',
      Popper: 'popper.js/dist/umd/popper',
    }),
```

And these my imports on my entry point

```
import 'bootstrap-material-design/dist/css/bootstrap-material-design.css';
import 'bootstrap-material-design/dist/js/bootstrap-material-design';

$(document).ready(() => { $('body').bootstrapMaterialDesign(); });
```
