### ISSUE TITLE
ripple.min.js could not be found on ng serve

### ISSUE THREAD

**Issue by ShadabFaiz** [mdbootstrap/mdb-ui-kit#1352]
#### Summary

I have updated my project from Angular ver 4.4.4 to ver. 7.2.7. I have updated the bootstrap, material-bootstrap-design and jquery version also. So now, these are their version:
``` typescript
"bootstrap": "4.3.1",
"bootstrap-material-design": "4.1.1",
 "jquery": "3.3.1",
 "jquery-ui-dist": "^1.12.1",
```
#### Expected result

`ng serve` should run without any problem
#### Additional Information
`ng serve` now gives the following error:
``` typescript
** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **
 92% additional asset processing scripts-webpack-plugin✖ ｢wdm｣: Error: ENOENT: no such file or directory, open '/home/Faiz/GitRepos/Goatry/goatry_admin/node_modules/bootstrap-material-design/dist/js/ripples.min.js'
    at Object.openSync (fs.js:439:3)
    at Object.readFileSync (fs.js:344:35)
    at Storage.provideSync (/home/Faiz/GitRepos/Goatry/goatry_admin/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:98:13)
    at CachedInputFileSystem.readFileSync (/home/Faiz/GitRepos/Goatry/goatry_admin/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:259:32)
    at Observable.rxjs_1.Observable.obs [as _subscribe] (/home/Faiz/GitRepos/Goatry/goatry_admin/node_modules/@ngtools/webpack/src/webpack-input-host.js:35:51)
    at Observable._trySubscribe (/home/Faiz/GitRepos/Goatry/goatry_admin/node_modules/@ngtools/webpack/node_modules/rxjs/internal/Observable.js:44:25)
    at Observable.subscribe (/home/Faiz/GitRepos/Goatry/goatry_admin/node_modules/@ngtools/webpack/node_modules/rxjs/internal/Observable.js:30:22)
    at SyncDelegateHost._doSyncCall (/home/Faiz/GitRepos/Goatry/goatry_admin/node_modules/@ngtools/webpack/node_modules/@angular-devkit/core/src/virtual-fs/host/sync.js:22:20)
    at SyncDelegateHost.read (/home/Faiz/GitRepos/Goatry/goatry_admin/node_modules/@ngtools/webpack/node_modules/@angular-devkit/core/src/virtual-fs/host/sync.js:49:21)
    at WebpackCompilerHost.readFileBuffer (/home/Faiz/GitRepos/Goatry/goatry_admin/node_modules/@ngtools/webpack/src/compiler_host.js:125:44)
    at VirtualFileSystemDecorator.readFile (/home/Faiz/GitRepos/Goatry/goatry_admin/node_modules/@ngtools/webpack/src/virtual_file_system_decorator.js:39:54)
    at Promise (/home/Faiz/GitRepos/Goatry/goatry_admin/node_modules/@angular-devkit/build-angular/src/angular-cli-files/plugins/scripts-webpack-plugin.js:69:49)
    at new Promise (<anonymous>)
    at scripts.map.fullPath (/home/Faiz/GitRepos/Goatry/goatry_admin/node_modules/@angular-devkit/build-angular/src/angular-cli-files/plugins/scripts-webpack-plugin.js:68:24)
    at Array.map (<anonymous>)
    at hook (/home/Faiz/GitRepos/Goatry/goatry_admin/node_modules/@angular-devkit/build-angular/src/angular-cli-files/plugins/scripts-webpack-plugin.js:67:43)
```

This error does not appear on the newly create angular 7.2.7 project.

**Comment by FezVrasta** [comment]
Have you upgraded from v3 to v4? That may be the issue. The API changed

**Comment by ShadabFaiz** [comment]
Yes. My mistake. It turns out ripple.min.js does not exist now and I had it include in angular-cli.json in ver 4.4.4.
