### ISSUE TITLE
Error building v4.1.3

### ISSUE THREAD

**Issue by realsama** [mdbootstrap/mdb-ui-kit#1409]
I am trying to build the released v4.1.3 on a windows 10 x64 system and i am getting an error installing the project dependencies. Once I **npm install**, i get a stacktrace

```
js/index.js → dist/js/bootstrap-material-design.js...
(!) Error when using sourcemap for reporting an error: Can't resolve original location of error.
js\baseInput.js: (1:9)
[!] Error: 'createForOfIteratorHelperLoose' is not exported by  rollupPluginBabelHelpers.js, imported by js\baseInput.js
https://rollupjs.org/guide/en/#error-name-is-not-exported-by-module
js\baseInput.js (1:9)
1: import Base from "./base";
            ^
2: import Util from "./util";
Error: 'createForOfIteratorHelperLoose' is not exported by  rollupPluginBabelHelpers.js, imported by js\baseInput.js
    at error (C:\Users\SAM\Desktop\bootstrap-material-design-4.1.3\node_modules\rollup\dist\shared\node-entry.js:5400:30)
    at Module.error (C:\Users\SAM\Desktop\bootstrap-material-design-4.1.3\node_modules\rollup\dist\shared\node-entry.js:9824:16)
    at handleMissingExport (C:\Users\SAM\Desktop\bootstrap-material-design-4.1.3\node_modules\rollup\dist\shared\node-entry.js:9725:28)
    at Module.traceVariable (C:\Users\SAM\Desktop\bootstrap-material-design-4.1.3\node_modules\rollup\dist\shared\node-entry.js:10163:24)
    at ModuleScope.findVariable (C:\Users\SAM\Desktop\bootstrap-material-design-4.1.3\node_modules\rollup\dist\shared\node-entry.js:8770:39)
    at FunctionScope.findVariable (C:\Users\SAM\Desktop\bootstrap-material-design-4.1.3\node_modules\rollup\dist\shared\node-entry.js:3065:38)
    at ChildScope.findVariable (C:\Users\SAM\Desktop\bootstrap-material-design-4.1.3\node_modules\rollup\dist\shared\node-entry.js:3065:38)
    at FunctionScope.findVariable (C:\Users\SAM\Desktop\bootstrap-material-design-4.1.3\node_modules\rollup\dist\shared\node-entry.js:3065:38)
    at ChildScope.findVariable (C:\Users\SAM\Desktop\bootstrap-material-design-4.1.3\node_modules\rollup\dist\shared\node-entry.js:3065:38)
    at FunctionScope.findVariable (C:\Users\SAM\Desktop\bootstrap-material-design-4.1.3\node_modules\rollup\dist\shared\node-entry.js:3065:38)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bootstrap-material-design@4.1.2 build:js: `rollup js/index.js --output.file=dist/js/bootstrap-material-design.js -m --config=rollup.config.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bootstrap-material-design@4.1.2 build:js script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by csaltos** [comment]
I have the same error and I'm lost :( ... at rollup commonjs plugin they said that namedExports is deprecated and without that bootstrap-material-design is broken until further fix

**Comment by realsama** [comment]
@csaltos found a fork with bootstrap 4.5 and my features implemented already.

**Comment by csaltos** [comment]
Great !! ... which is the fork ?

**Comment by vitfury** [comment]
@shepherd1530 So why don't you left the link here? Faced with same problem

**Comment by csaltos** [comment]
I decided to move from Bootstrap to Svelte in my company ... it's more modern and powerful ... please find here a starter tool with a Material UI with Svelte -> https://smeltejs.com/

More info at https://dev.to/csaltos/sapper-with-material-ui-35id
