### ISSUE TITLE
TypeError: jhipsterFunc.addAngularJsConfig is not a function

### ISSUE THREAD

**Issue by alinturbut** [mdbootstrap/mdb-ui-kit#934]
I follow the steps needed for configuration and I get this:

```
Composing JHipster configuration with module bootstrap-material-design
Reading the JHipster project configuration for your module
events.js:141
      throw er; // Unhandled 'error' event
      ^

TypeError: jhipsterFunc.addAngularJsConfig is not a function
    at module.exports.yeoman.generators.Base.extend.writing (C:\Users\aturbut\AppData\Roaming\npm\node_modules\generator-jhipster-bootstrap-material-design\generators\app\index.js:70:22)
    at C:\Users\aturbut\AppData\Roaming\npm\node_modules\generator-jhipster-bootstrap-material-design\node_modules\yeoman-generator\lib\base.js:430:16
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

**P.S.** I have previously used this generator and it worked properly. Any help is apreciated :)

**Comment by rosskevin** [comment]
It doesn't appear that this issue is related to the JS or CSS from this project.  Please try the repo for the generator.
